import { BannerSlide, FeaturedProject, Differentiator, MapProject, FeaturedFlat } from "@/shared/interface";

export const HOME_SEED_OBJ = {
  bannerSlides: [
    {
      id: 1,
      image: "/banner-6.png",
      title: "Book Your\nDream Apartment\nin Trusted Projects",
      subtitle:
        "Modern living spaces in prime locations.\nDesigned for comfort, built for life.",
      projectName: "Swapno Neer",
      location: "Gulshan-2, Dhaka",
      price: "৳ 1,85,00,000",
      totalFloor: "G+10",
      units: "2",
      parking: "Yes",
      gym: "Yes",
    },
    {
      id: 2,
      image: "/banner-5.png",
      title: "Luxury Living\nRedefined for\nModern Families",
      subtitle:
        "Spacious apartments with world-class amenities.\nYour perfect home awaits.",
      projectName: "Nilima Tower",
      location: "Dhanmondi, Dhaka",
      price: "৳ 2,45,00,000",
      totalFloor: "G+12",
      units: "2",
      parking: "Yes",
      gym: "Yes",
    },
    {
      id: 3,
      image: "/banner-3.png",
      title: "Invest in\nPremium Real Estate\nwith Confidence",
      subtitle:
        "Transparent dealings and trusted developers.\nSecure your future today.",
      projectName: "Shonali Kunj",
      location: "Banani, Dhaka",
      price: "৳ 3,10,00,000",
      totalFloor: "G+14",
      units: "2",
      parking: "Yes",
      gym: "Yes",
    },
    {
      id: 4,
      image: "/banner-7.png",
      title: "Find Your\nIdeal Home in\nPrime Locations",
      subtitle:
        "Hand-picked properties in the best neighborhoods.\nQuality you can trust.",
      projectName: "Surma Haven",
      location: "Uttara, Dhaka",
      price: "৳ 1,50,00,000",
      totalFloor: "G+9",
      units: "2",
      parking: "Yes",
      gym: "Yes",
    },
  ] as BannerSlide[],

  featuredProjects: [
    {
      id: 1,
      image: "/building-01.png",
      projectName: "Swapno Neer",
      location: "Gulshan-2, Dhaka",
      totalFloor: "G+10",
      unitsPerFloor: "2",
      size: "1,650 Sft",
    },
    {
      id: 2,
      image: "/building-02.png",
      projectName: "Nilima Tower",
      location: "Dhanmondi, Dhaka",
      totalFloor: "G+12",
      unitsPerFloor: "2",
      size: "1,850 Sft",
    },
    {
      id: 3,
      image: "/building-03.png",
      projectName: "Shonali Kunj",
      location: "Banani, Dhaka",
      totalFloor: "G+14",
      unitsPerFloor: "2",
      size: "2,100 Sft",
    },
    {
      id: 4,
      image: "/building-04.png",
      projectName: "Surma Haven",
      location: "Uttara, Dhaka",
      totalFloor: "G+9",
      unitsPerFloor: "2",
      size: "1,450 Sft",
    },
  ] as FeaturedProject[],

  differentiators: [
    {
      id: 1,
      title: "EXPERIENCE",
      description: "With more than 50 years of expertise in construction and real estate, we bring proven knowledge and reliability to every project.",
      iconName: "experience",
    },
    {
      id: 3,
      title: "TRUST",
      description: "We have successfully delivered over 10,000 units across more than 1,200 projects, earning the confidence of countless customers.",
      iconName: "trust",
    },
    {
      id: 4,
      title: "QUALITY",
      description: "We maintain strict standards in every stage of development, ensuring lasting quality, safety, and refined finishing.",
      iconName: "quality",
    },
    {
      id: 5,
      title: "DESIGN",
      description: "We believe great design is not only about appearance, but also comfort, functionality, and long-term value.",
      iconName: "design",
    },
  ] as Differentiator[],

  mapProjects: [
    {
      id: 1,
      projectName: "Swapno Neer",
      locationName: "Gulshan-2, Dhaka",
      lat: 23.7925,
      lng: 90.4178,
    },
    {
      id: 2,
      projectName: "Nilima Tower",
      locationName: "Dhanmondi, Dhaka",
      lat: 23.7461,
      lng: 90.3742,
    },
    {
      id: 3,
      projectName: "Shonali Kunj",
      locationName: "Banani, Dhaka",
      lat: 23.7937,
      lng: 90.4066,
    },
    {
      id: 4,
      projectName: "Surma Haven",
      locationName: "Uttara, Dhaka",
      lat: 23.8759,
      lng: 90.3795,
    },
    {
      id: 5,
      projectName: "Meghna Niloy",
      locationName: "Bashundhara R/A, Dhaka",
      lat: 23.8188,
      lng: 90.4312,
    },
    {
      id: 6,
      projectName: "Baily Bithi",
      locationName: "Baily Road, Dhaka",
      lat: 23.7405,
      lng: 90.4005,
    },
    {
      id: 7,
      projectName: "Ruposhi Bangla",
      locationName: "Mirpur-10, Dhaka",
      lat: 23.8069,
      lng: 90.3687,
    },
    {
      id: 8,
      projectName: "Padma Heights",
      locationName: "Mohakhali DOHS, Dhaka",
      lat: 23.7802,
      lng: 90.3950,
    },
  ] as MapProject[],

  featuredFlats: [
    {
      id: 1,
      image: "/flat-1.png",
      tag: "Swapno Neer",
      title: "SN-1A - Premium Flat",
      location: "Gulshan-2, Dhaka",
      beds: 3,
      baths: 3,
      size: "1650 Sqft",
      price: "৳ 1,85,00,000",
    },
    {
      id: 2,
      image: "/flat-2.png",
      tag: "Shonali Kunj",
      title: "SK-1B - Comfort Flat",
      location: "Banani, Dhaka",
      beds: 2,
      baths: 2,
      size: "1200 Sqft",
      price: "৳ 1,25,00,000",
    },
    {
      id: 3,
      image: "/flat-3.png",
      tag: "Nilima Tower",
      title: "NT-2A - Luxury Flat",
      location: "Dhanmondi, Dhaka",
      beds: 3,
      baths: 3,
      size: "1550 Sqft",
      price: "৳ 1,75,00,000",
    },
    {
      id: 4,
      image: "/flat-4.png",
      tag: "Meghna Niloy",
      title: "MN-3B - Exclusive Flat",
      location: "Bashundhara R/A, Dhaka",
      beds: 4,
      baths: 4,
      size: "2200 Sqft",
      price: "৳ 2,60,00,000",
    },
  ] as FeaturedFlat[],
};
