import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import PublicHeaderMenu from "@/menus/publicHeaderMenu/PublicHeaderMenu";
import PublicFooterMenu from "@/menus/publicFooterMenu/PublicFooterMenu";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/logo-icon-white-bg.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="">
        <PublicHeaderMenu />
        <main className="flex-1">
          {children}
        </main>
        <PublicFooterMenu />
      </body>
    </html>
  );
}
